spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:///vhr?serverTimezone=GMT%2B8
############################################################
#
# mybatis \u914D\u7F6E
#
############################################################
mybatis:
  type-aliases-package: com.goudan.pojo          # \u6240\u6709POJO\u7C7B\u6240\u5728\u5305\u8DEF\u5F84
  mapper-locations: classpath:mapper/*.xml      # mapper\u6620\u5C04\u6587\u4EF6
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #\u63A7\u5236\u53F0\u663E\u793ASQL\u8BED\u53E5